### ISSUE TITLE
Advanced search filter has no effect

### ISSUE THREAD

**Issue by gitraphha** [bramley/phplist-plugin-subscribers#17]
Dear all,
the advanced search filter is not working for me.
For example:
some of my subscribers' emails contain the string "raph". If I search for these as shown in the screenshots, _all_ subscribers are shown. Same result when searching for (not) confirmed or blacklisted subscribers. Also the seach values entered ("raph" or "confirmed only") don't show after I click on "Show".
The filter does however work when used on the "subscriber commands" page - when I click on "Match", the correct subset of subscribers is selected.
Also the native Find subscribers filter works as expected. Also the search value "raph" still shows after clicking on "go"
Am I missing something when doing the advanced search?

Thanks for your help and best regards,
Raphael

PHP Version 7.4.29
phpList v3.6.8
Plugins:
    Common Pluginversion 3.18.4+20220421 by Duncan Cameron
    Disposable email address blockerversion 0.1 by Michiel Dethmers
    Date placeholderversion 0.2 by Michiel Dethmers
    CKEditor pluginversion 2.6.6+20220515 by Duncan Cameron
    Segmentationversion 2.12.1+20210428 by Duncan Cameron
    Subscribers Pluginversion 2.31.0+20220112 by Duncan Cameron

![1-1_AdvancedFindSubscribers](https://user-images.githubusercontent.com/38692288/173846402-26c38e30-6882-450a-9009-4585c7b918e0.jpeg)
![1-2_AdvancedSearchResults](https://user-images.githubusercontent.com/38692288/173846410-f5281abd-cba6-42bd-8ec5-7612f539771c.jpeg)
![2-1_SubscrCommands](https://user-images.githubusercontent.com/38692288/173846412-2ea56342-6f72-45af-806d-7235763db518.jpeg)
![2-2_ConfirmActions](https://user-images.githubusercontent.com/38692288/173846415-811c1349-54a8-4978-9e79-1edafc436fb1.jpeg)

**Comment by bramley** [comment]
Is there anything special about the value "raph", or does the Advanced Search not work for any value?

**Comment by bramley** [comment]
What is the length of the admin user id that you are using?

**Comment by gitraphha** [comment]
I use my email address: webmaster@xxxxxxxxx.de, so the length is 22

**Comment by bramley** [comment]
Ah, that is a problem. The plugin stores the search criteria in the phplist config table using a key comprised of a 15 character constant and the admin name. Because the table column has a maximum size of 35 characters, any admin name longer than 20 characters is going to be truncated.

When the plugin page tries to display the search results it doesn't find the table row that it is looking for, so defaults to displaying all subscribers.

To work around this, just use a shorter admin name (you can change that on the manage administrators page).
I will look into this to see if there is a simple way to remove that restriction.

**Comment by gitraphha** [comment]
yeah, great. I can confirm it works like a charm with a 9-char admin username.
All the mentioned issues and irritations are gone.
Thanks again for your quick help!
